---
333:
  strategy:
    Duplicate: {}
  destinations:
    - Address: "127.1.0.1:3333"
    - Address: "127.1.100.88:3333"
    - Group:
        strategy:
          RoundRobin: {}
        destinations:
          - Address: "127.1.1.1:2222"
          - Address: "127.1.1.2:2222"

334:
  strategy:
    RoundRobin: {}
  destinations:
    - Address: "127.1.0.1:3333"
    - Address: "127.1.100.88:3333"
    - Group:
        strategy:
          RoundRobin: {}
        destinations:
          - Address: "127.1.20.1:2222"
          - Address: "127.1.20.2:2222"

335:
  strategy:
    Duplicate: {}
  destinations:
    - Group:
        strategy:
          RoundRobin: {}
        destinations:
          - Address: "127.1.1.1:2222"
          - Address: "127.1.1.2:2222"
    - Group:
        strategy:
          RoundRobin: {}
        destinations:
          - Address: "127.1.20.1:2222"
          - Address: "127.1.20.2:2222"
          - Group:
              strategy:
                Duplicate: {}
              destinations:
                - Address: "127.1.30.1:2222"
                - Address: "127.1.30.2:2222"
